### ISSUE TITLE
コンソールから実行した際に join subprocess と表示されるが output フォルダに画像が生成されない

### ISSUE THREAD

**Issue by si-ryao** [sugarkwork/mozaikukun#7]
次の手順に沿って実行しましたが、画像のアウトプットがされません。

実行した手順
`Create an "input" directory.
Put the image you want to mosaic in the input directory.
Run: python mozaikukun.py
An output directory will be created and the layers of the mosaicked image will be output.`

結果
`Start processing...
start subprocess 1
start subprocess 0
start subprocess 2
exit subprocess 1
exit subprocess 0
exit subprocess 2
join subprocess : <Process name='Process-1' pid=6680 parent=27220 stopped exitcode=0>
join subprocess : <Process name='Process-2' pid=38448 parent=27220 stopped exitcode=0>
join subprocess : <Process name='Process-3' pid=38656 parent=27220 stopped exitcode=0>`

何か手順が間違っていますか？

**Comment by sugarkwork** [comment]
今現在、input ディレクトリ配下の *.jpg を探しているので、JPEG 以外は認識されません。
処理させようとしている画像は、png だったりしますか？

**Comment by sugarkwork** [comment]
まだ確認が取れた訳ではありませんが、jpg 以外にも png や webp なんかを受け付けられるように修正しました。
git pull コマンドで更新して、最新のコミットを試してみてください。

**Comment by si-ryao** [comment]
ありがとうございます、拡張子の問題でした。
アップデートしていただいた内容を試してみます、ご対応いただきありがとうございました。
